Bcfg2/bcfg2

doc/server/plugins/structures/bundler/bcfg2.txt, doc/server/plugins/structures/bundler/index.txt, schemas/bundle.xsd, src/lib/Bcfg2/Client/Tools/BundleDeps.py, src/lib/Bcfg2/Client/__init__.py, src/lib/Bcfg2/Server/Plugins/Bundler.py, testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestBundler.py
Bundle dependencies are now realized with RequiredBundle and support inheritance of the modification flag. This requires new client support and will only work with clients >= 1.4.0pre2.
The new tag name is required for validation. The tag name and type association in the schema has to be unambiguous and we need nested bundle tags for xincludes. Bundle dependency are only available in 1.4.0pre1, so I do not know if we need a migration script that renames the empty bundle tags to RequiredBundle.
=> Bundler: add modification support to Bundle dependencies

testsuite/ext/ssl_protocols.py, testsuite/pylintrc.conf, testsuite/requirements.txt
The new version of python-daemon is broken (at least pre-python2.7 support was dropped). This maybe fixes the recent travis error.
=> testsuite/requirements: python-daemon >= 2.0.0 is broken

src/lib/Bcfg2/Server/FileMonitor/Pseudo.py, src/lib/Bcfg2/Server/Plugins/Decisions.py
Currently the Decisions plugin does not work because it does not monitors the files. The first patch add the monitoring and the second patch fixes the pseudo filemonitor for not generating the initial exists events, if the file does not exists.
=> Fix Decisions Plugin

src/lib/Bcfg2/Client/Tools/Pkgng.py
By default pkg search will update the local copy of the repository
catalogue from remote. We are executing a lot of searches and do
not want to update the catalogue every time.
=> Client/Tools/Pkgng: No auto-update on pkg-search.

src/lib/Bcfg2/Client/Tools/APT.py
In ee4111fc we removed the wrong continue (the one after the if/else block
for newapi) and now we get an error that 'auto' is not an available version.
=> Client/Tools/APT: Fix regression of ee4111fc

doc/releases/1.3.6.txt, src/lib/Bcfg2/Server/Plugins/Metadata.py
If the auth type (either globally or specific for the client) is set to cert auth,
we have to reject clients that does not provide a cert.
=> Server/Plugins/Metadata: Reject passwd clients, if auth_type is cert

src/lib/Bcfg2/Server/Plugins/Packages/Source.py, src/lib/Bcfg2/Server/Plugins/Packages/Yum.py
During ``__init__`` of the parent class ``get_repo_name`` is called. That needs
fields (``pump_id``) that are defined later in the ``__init__`` of YumSource.
We introduce the new function ``_init_attributes`` to parse all attributes
out of the ``<Source>`` tag before calling any other functions.
=> Plugins/Packages: fix initialization of YumSource

src/lib/Bcfg2/Client/Tools/APT.py, src/lib/Bcfg2/Client/Tools/MacPorts.py, src/lib/Bcfg2/Client/Tools/POSIXUsers.py, src/lib/Bcfg2/Client/Tools/YUM.py, src/lib/Bcfg2/Client/Tools/__init__.py, src/lib/Bcfg2/Server/FileMonitor/__init__.py, src/lib/Bcfg2/Server/Lint/Validate.py, src/lib/Bcfg2/Server/Lint/ValidateJSON.py, src/lib/Bcfg2/Server/Lint/__init__.py, src/lib/Bcfg2/Server/Plugin/__init__.py, src/lib/Bcfg2/Server/Plugins/GroupPatterns.py, src/lib/Bcfg2/Server/Plugins/SSLCA.py, src/sbin/bcfg2-test, testsuite/requirements.txt
This also pins pylint to <= 0.28 so we don't have to keep playing
whack-a-mole with it.
Also removes unnecessary suppression of apt warnings. This is no
longer necessary in 12.04, so should be safe to remove. If you're on
Ubuntu < 12.04, upgrade for heaven's sake.
=> Fix pylint errors

src/lib/Bcfg2/Client/Tools/APT.py, src/lib/Bcfg2/Client/Tools/Pkgng.py, src/lib/Bcfg2/Client/Tools/__init__.py, src/lib/Bcfg2/Reporting/Storage/DjangoORM.py
The handling of the reporting of extra packages was a bit strange. The version of the extra package was reported as `target_version` in the reporting. Only yum/rpm packages with a nested `<Instance>` tag parsed the version as current_version.
=> Fix extra packages

src/lib/Bcfg2/Server/Plugins/Packages/Source.py
``_init_attributes`` should be called after all properties of the ``Source`` class
are initialized (so that ``_init_attributes`` could overwrite some of it).
The ``Yum`` class initializes ``self.deps`` with a different default entry, that
should not be reset by ``__init__`` of ``Source`` afterwards.
=> Server/Plugins/Packages: Fix _init_attributes position.

src/lib/Bcfg2/Server/Plugins/Packages/Yum.py
This commit helps the internal YUM resolver to choose the latest version
of a package to generate dependencies. Previously, we were simply
iterating through the file so that the last instance listed always won
(even if that instance was an older version with differing
dependencies).
=> Packages/Yum.py: Fix dependency resolution logic

src/lib/Bcfg2/Client/Tools/POSIX/base.py, src/lib/Bcfg2/Options.py
- adds 'secontext_ignore' under POSIX in the configuration file
- short circuits on filesystems that are known not to support file labels
- defaults to filesystems that have a genfs command in selinux reference policy
- checks for Operation not supported while setting a file label
- fixes #275
=> handle filesystem secontexts properly for contextless filesystems

src/lib/Bcfg2/Server/Plugins/Packages/Yum.py
Sometimes repositories may not contain packages for a specific
architecture group. This handles that case gracefully instead of causing
a traceback and failing to bind all Package entries.
=> Yum.py: Fix traceback when arch missing

src/lib/Bcfg2/Server/Plugins/SSHbase.py
This fixes two small things in SSHbase:
* The logging call is a regression from 3d06f3112 (and therefor the error is not found in miant).
* The exception types are also wrong in maint, but it does not break things there, because in maint there is a wildcard except around.
=> Some small fixes for SSHbase

tools/upgrade/1.3/migrate_info.py, tools/upgrade/1.3/migrate_perms_to_mode.py
Hi,
the migration to the new parser for Options has introduced some small issues in tools/. The new parser does not read the Plugin names from the config but instantiates the full Plugin classes. So we need `__name__` to access the raw name.
Another issue is, that the components should be specified as list, even if it is only one.
Alex
=> Fix some issues with new Options parser in tools/

src/lib/Bcfg2/Server/Plugin/helpers.py
This is used for the Rules and Defaults plugins. Without this patch all text
content that was there before (for example file content bound by Cfg) is lost,
for all entries specified in Defaults.
=> PrioDir: Only set text content, if something is available

src/lib/Bcfg2/Client/Tools/POSIX/File.py, src/lib/Bcfg2/Server/Lint/MergeFiles.py, src/lib/Bcfg2/Utils.py, testsuite/Testsrc/Testlib/TestClient/TestTools/TestPOSIX/TestFile.py, testsuite/Testsrc/Testlib/TestUtils.py
Ignore files with binary content, because SequenceMatcher seems to have problems
and sometimes detect files with different content as identically.
=> Lint/MergeFiles: Ignore binary files

src/lib/Bcfg2/Client/Tools/Systemd.py
Taken directly from master (ref 33e53dde2a85b8783c8e4935868d9c5f50dea440).
Only a minor change, using:
self.setup['servicemode']
instead of:
Bcfg2.Options.setup.servicemode
This change is needed because the Systemd tool in maint is horribly out of date, and doesn't fully manage systemd services.  For example, the VerifyService function didn't check whether services were enabled/disabled, just whether they were running or not.
=> Systemd: Backport the code from master into maint

doc/man/bcfg2.conf.txt, doc/releases/1.4.0pre2.txt, man/bcfg2.conf.5, src/lib/Bcfg2/DBSettings.py, src/lib/Bcfg2/Options/Types.py, src/lib/Bcfg2/Reporting/templates/base-timeview.html, src/lib/Bcfg2/Reporting/templates/clients/detail.html, src/lib/Bcfg2/Reporting/templates/clients/detailed-list.html, src/lib/Bcfg2/Reporting/templates/config_items/entry_status.html, src/lib/Bcfg2/Reporting/templates/config_items/item.html, src/lib/Bcfg2/Reporting/templates/widgets/interaction_list.inc, testsuite/Testsrc/Testlib/TestOptions/TestTypes.py, testsuite/common.py
I wanted to customize the date and time formats used in the reporting web interface. This is the way to do it with django. I could now use something like ``django_settings = USE_L10N=true, LANGUAGE_CODE=de-DE`` and get correct German date formats.
=> Fix date format

doc/releases/1.4.0pre2.txt, src/lib/Bcfg2/DBSettings.py, src/lib/Bcfg2/Options/Types.py, testsuite/Testsrc/Testlib/TestOptions/TestTypes.py
This is mostly from 257eb0c17 and 16d3e04cb to allow for setting arbitrary
database options since some settings require nested dictionaries, etc.
This got lost during merge from maint into master because of the completely
different Options parsing.
=> Options/Types: Fix database OPTIONS parsing

src/lib/Bcfg2/Client/Tools/Systemd.py
If bootstatus is set to something and status is set to ignore for a systemd service,
we do not want to stop this service.
=> Client/Tools/Systemd: Do not stop services if status is set to ignore

src/lib/Bcfg2/Options/Parser.py, testsuite/Testsrc/Testlib/TestOptions/TestComponents.py, testsuite/Testsrc/Testlib/TestOptions/Two.py
If adding an option during the "Main Parser Loop" (for example because of loading
a component for bcfg-lint) a value for the option from the config file is simply
ignored.
After adding the option the parser first tries to find the value in the command line,
but cannot find it and set the default value from the source code as option value.
After that the value from the config file is set as new default. But because the
option already is in the Namespace, it does not use the new "default" value from the
config file.
This patch simply sets the default value from the config file, right after the new option
is added to the parser and so the correct value is used afterwards, if the parsed cannot
find the flag on the command line.
=> Options: Set default values from config, right after adding a new option

src/lib/Bcfg2/Server/Plugins/Cfg/CfgJinja2Generator.py
If jinja2 is not available, we cannot use some classes. So the access to
these classes have to be dependent on the available of jinja2.
I do not know, if it is good to have an if around assignments on class level. As an alternative we could create two dummy classes (`def Environment(object): pass` or something like that) if jinja2 is not available.
=> Plugins/Cfg: Don't depend on jinja2

doc/server/plugins/generators/cfg.txt
Seems current description was added in https://github.com/Bcfg2/bcfg2/commit/255046b3f3484219bbfa6646c88bbc4bbc1b5256 , but is not valid anymore.
Corresponding code:
https://github.com/Bcfg2/bcfg2/blob/master/src/lib/Bcfg2/Server/Core.py#L633
`name` corresponds to `altsrc` only when `realname` attribute is also present; and in https://github.com/Bcfg2/bcfg2/blob/master/src/lib/Bcfg2/Server/Plugin/helpers.py#L107 `realname` has the precedence over `name`.
=> doc: update Genshi 'name' attribute description

doc/releases/1.4.0pre2.txt, doc/server/plugins/generators/rules.txt, doc/server/plugins/structures/defaults.txt, src/lib/Bcfg2/Server/Plugin/helpers.py, src/lib/Bcfg2/Server/Plugins/Defaults.py, src/lib/Bcfg2/Server/Plugins/Rules.py, testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestDefaults.py, testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestRules.py, testsuite/common.py
If you use the regex feature of Rules/Defaults you may need the real name
of the matched entry in an attribute (for example home of POSIXUser).
You can now enable replace_name for rules or defaults and ${name} will be
replaces in the attribues of the Element before adding them to the target
entry.
This allows you to write something like that in Defaults to assing a default
home directory somewhere else to all users with unset home:
<POSIXUser name='.*' home='/somewhere/${name}'/>
=> Rules: New options replace_name to replace ${name} in attributes

src/lib/Bcfg2/Server/Plugins/Cfg/CfgJinja2Generator.py
Jinja 2 strips a trailing newline from templates by default.  In 2.7, an option was introduced to change this behavior.  Removing the newline breaks some configuration files, such as the iptables state file.
=> Keep trailing newlines in Jinja2 templates.

src/lib/Bcfg2/Logger.py
The `logging.LogRecord` instance could contain `args` to replace some
placeholders in the format string in `msg`.
=> Logging: Fix message building

misc/bcfg2.spec
These changes are required in order for bcfg2 to run if installed from a clean, minimal installation.
=> Include recent changes in RPM spec dependencies.

src/lib/Bcfg2/Server/Plugins/Bundler.py
`bundles` is a set and does only have `add()` but not `append()`.
=> Bundler: Fix addition of bundle.

testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestBundler.py
This fixes the testsuite for Bundler. The Metadata plugin always initialize the bundles as set and so the testsuite should do the same.
=> testsuite: metadata.bundles shoud be a set()

src/lib/Bcfg2/Server/FileMonitor/Inotify.py
The superclass sets self.started to False which makes sure the logic works correctly and notifier.stop() does not get run more than once.
=> Run the superclass shutdown() to correctly set self.started

src/lib/Bcfg2/Server/Admin.py
This adds `schemamigration` as a new `bcfg2-admin` subcommand, so while developing one could update the south migrations easily.
=> bcfg2-admin: Add schemamigration command from south

doc/development/plugins.txt, src/lib/Bcfg2/Server/Plugins/AWSTags.py, src/lib/Bcfg2/Server/Plugins/GroupLogic.py, src/lib/Bcfg2/Server/Plugins/Ohai.py, src/lib/Bcfg2/Server/Plugins/Probes.py, src/lib/Bcfg2/Server/Plugins/Properties.py, src/lib/Bcfg2/Server/Plugins/PuppetENC.py, src/lib/Bcfg2/Server/Plugins/SSHbase.py, src/lib/Bcfg2/Server/Plugins/TemplateHelper.py, testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestProperties.py, testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestTemplateHelper.py
The plugins need to expire the metadata_cache, even if they only implement `Bcfg2.Server.Plugin.interfaces.Connector.get_additional_data`. This expires the
metadata_cache in all plugins and updates to docs.
The AWSTags plugin is incompatible with aggressive caching mode (like PuppetEnc).
Maybe we should do something like with Packages. The plugins cache the results
indefinitely and it can be refreshed with an xcmd command, but that would be another
pull request.
=> Expire metadata cache in all Connector plugins.

src/lib/Bcfg2/Client/Tools/APT.py, src/lib/Bcfg2/Client/Tools/Pkgng.py
`Install()` of a client tool returns the changed states as dict, that will update
the global state. If nothing is handled withing a tool, it have to return an empty
dict and not None because the return value is directly used as argument for update:
> APT.Install() call failed:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/Bcfg2/Client/__init__.py", line 739, in DispatchInstallCalls
>    self.states.update(tool.Install(handled))
> TypeError: 'NoneType' object is not iterable
=> Client/Tools: Fix error if no pkg handled

testsuite/Testsrc/Testlib/TestClient/TestTools/TestPOSIXUsers.py, testsuite/common.py
mock-1.1.0 was converted to a package and needs to be imported differently.
=> testsuite: Require newer version of mock and change import

src/lib/Bcfg2/Server/Lint/TemplateHelper.py
The HelperModules of the TemplateHelper now expects a second argument with
the core, to be able to expire the metadata cache.
This is a fix-up for 36b2aa66627a4cc147f982d03688ae9df14bbe08.
=> Lint/TemplateHelper: Fix parameters

src/lib/Bcfg2/Client/__init__.py
If diff output contains non-ascii characters, then the first call to safe_input in prompt() will raise UnicodeEncodeError.  prompt will then use input(), which will fail under python2.
This change uses safe_input() in both cases.
=> Don't use 'input' function under python2.

src/lib/Bcfg2/Server/Plugins/Packages/Yum.py, src/lib/Bcfg2/Server/Plugins/Packages/YumHelper.py
With the new options code, classes used as the parent argument to register_commands must not access the setup object in their init function, because that object hasn't been prepared yet. It's best, then, not to have an init function at all.
Various other changes were made to get bcfg2-yum-helper working again.
=> Fix a variety of problems with YumHelper

testsuite/Testsrc/Testlib/TestClient/TestTools/TestPOSIXUsers.py, testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestProbes.py, testsuite/common.py
This is a backport of #326 for maint. So that we can fix the test cases for other fixes like #329.
=> testsuite: Change imports for newer mock versions (maint)

src/lib/Bcfg2/Reporting/templates/clients/detailed-list.html, src/lib/Bcfg2/Reporting/templates/widgets/interaction_list.inc, src/lib/Bcfg2/Server/Plugins/Metadata.py
Here are some more django fixes:
* Fix the database backend for the Metadata plugin (requires the same handling for django1.7 like the reporting database backend with `django.setup()`)
* Add a remaining fix for django1.5, that was missing in 84a83ca. (The first parameter of the `url` template tag has to be quoted.)
* Use consistent syntax for the `url` template tag and remove deprecated (in django1.8) syntax. The `url` template tag should be called with an identifier and not with the python dotted path of a view function.
Hopefully the last django1.7 fixes ;)
=> Some more django fixes

doc/server/plugins/grouping/metadata.txt
From IRC: 
> AlexS[zedat]: This is a known limitation. Bundles can not be inside conditionals in Metadata/groups.xml.
=> doc: Clarification on negated groups

.travis.yml, testsuite/install.sh
This is just a quick fix: The new version of pip on travis does
fail when using the `--use-mirrors` option (to be fair, the option
was deprecated long time ago).
The real fix will be #297 (once it will be ready to merge).
=> travis-ci: Fix installation of dependencies

.travis.yml, doc/conf.py, doc/development/compat.txt, doc/releases/index.txt, doc/server/plugins/generators/packages.txt, doc/server/plugins/structures/bundler/index.txt, doc/unsorted/vim_snippet.txt, src/lib/Bcfg2/Server/Encryption.py, testsuite/Testsrc/test_doc.py, testsuite/install.sh
This fixes various small syntax errors in the documentation. It also adds a unit test to check for syntax errors and warnings (only enabled for the tests with python2.7 and optional dependencies).
=> Fix syntax errors in documentation

debian/control
According to the [Debian Python FAQ](https://wiki.debian.org/Python/FAQ), python-support has been deprecated in favor of dh-python.
=> debian/control: Replace python-support with dh-python

src/lib/Bcfg2/Client/__init__.py
If the client is using lxml.etree as ElementTree library, it is impossible to a single node two times in an ElementTree. The second append will remove the first insertion. We need to copy the node before appending it into the statistic tree.
The different behavior of the different ElementTree implementations can be checked with the following example scripts:
```python
import xml.etree.ElementTree as ET
e1 = ET.Element('test')
e2 = ET.Element('test2')
e1.append(e2)
e1.append(e2)
print ET.tostring(e1)
```
Output: `<test><test2 /><test2 /></test>`
```python
import lxml.etree as ET
e1 = ET.Element('test')
e2 = ET.Element('test2')
e1.append(e2)
e1.append(e2)
print ET.tostring(e1)
```
Output: `<test><test2/></test>`
=> Client: Fix reporting of modified entries

src/lib/Bcfg2/Server/Plugins/Packages/Apt.py
It's possible for dependency names in Debian and Ubuntu packages to end in ':any', which signifies that the architecture doesn't matter. This may cause the following message (or something similar) to be logged:
```
Packages: Got 4 unknown entries
Packages: ['python2.7:any', 'python3:any', 'python:any', 'python3.5:any']
```
This patch just strips the suffix from all dependency names that have it.
=> Packages: Strip ':any' suffix from APT dependencies

src/lib/Bcfg2/Server/models.py, testsuite/Testsrc/Testlib/TestServer/TestPlugin/Testhelpers.py, testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestMetadata.py, testsuite/Testsrc/Testlib/TestServer/TestPlugins/TestProbes.py, testsuite/common.py
This reverts again the _removed duplicate plugins option_ commit. Sorry for introduction the bug again. I think this was introduced, due to incomplete local tests. The database tests reused the sqlite3 file from earlier tests.
Now the tests remove the old database (with unlink) and recreate it from scratch once per TestCase.
=> testsuite: Fix database tests

src/lib/Bcfg2/Server/Admin/Perf.py, src/lib/Bcfg2/Server/Admin/Xcmd.py, src/lib/Bcfg2/Server/Plugins/Ohai.py
bcfg2-admin xcmd and perf are broken after commit a2b8b3282bc07e1db362d2edd51d2bee3e425d57
Ohai probe is unable to run on Ubuntu/Debian systems with /bin/dash as /bin/sh, due to syntax incompatibility with bash/csh
=> bcfg2-admin: pass SSL protocol option for perf and xcmd connections

src/lib/Bcfg2/Server/Plugins/Packages/Apt.py, src/lib/Bcfg2/Server/Plugins/Packages/Pac.py, src/lib/Bcfg2/Server/Plugins/Packages/Pkgng.py
The pkgnames should be reset before parsing the source files. If a package was
removed for a source, it should be removed from the pkgnames set, too. The
packages plugin should look for the next source containing the package.
=> Packages: Cleanup pkgnames

src/lib/Bcfg2/Client/Tools/POSIX/Augeas.py
If I don't have lxml installed on the client, I get the following:
```
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/Bcfg2/Client/Tools/__init__.py", line 201, in Inventory
states[entry] = func(entry, mods)
File "/usr/lib/python2.7/dist-packages/Bcfg2/Client/Tools/POSIX/__init__.py", line 94, in VerifyPath
ret = self._handlers[entry.get("type")].verify(entry, modlist)
File "/usr/lib/python2.7/dist-packages/Bcfg2/Client/Tools/POSIX/Augeas.py", line 248, in verify
for cmd in self.get_commands(entry):
File "/usr/lib/python2.7/dist-packages/Bcfg2/Client/Tools/POSIX/Augeas.py", line 233, in get_commands
for cmd in entry.iterchildren():
AttributeError: 'Element' object has no attribute 'iterchildren'
```
This patch removes calls to `getparent` and `iterchildren` from …
=> Client/Tools/POSIX: Avoid lxml features in Augeas

src/lib/Bcfg2/Server/Plugins/Cfg/CfgSSLCAKeyCreator.py
The previous check resulted in a "FutureWarning" and also did not work
as expected and reset the key values in every case.
=> Cfg: Fix SSLCA key generation

src/lib/Bcfg2/Client/Proxy.py
Previously, having a ca specified in the client bcfg2.conf which pointed
to a file that didn't exist resulted in the following:
Unknown failure: [Errno 2] No such file or directory (IOError)
Unknown failure: [Errno 2] No such file or directory (IOError)
Unknown failure: [Errno 2] No such file or directory (IOError)
Fatal error: Failed to declare version: Unknown failure: [Errno 2] No such file or directory (IOError)
This commit provides more information about the actual cause of the
issue.
=> Client/Proxy.py: Provide more useful error message

doc/server/plugins/generators/nagiosgen.txt, src/lib/Bcfg2/Server/Plugins/NagiosGen.py
Some small fixes for the NagiosGen plugin:
* Update documentation: The _backwards-compatibility layer_ was removed.
* Always include default group. This should fix #161.
* Small code cleanup. Why should you use a list if you want to have a set?!
=> Some small fixes for NagiosGen

src/lib/Bcfg2/DBSettings.py, src/lib/Bcfg2/Reporting/Reports.py, src/lib/Bcfg2/Reporting/Storage/DjangoORM.py, src/lib/Bcfg2/Server/Admin.py, src/lib/Bcfg2/Server/Plugins/Metadata.py, src/lib/Bcfg2/Server/Plugins/Probes.py
This should fix the bcfg2-report-collector for django-1.9 (#357). The import in `DjangoORM.py` is a bit messy, but it works.
This also removes all calls to `django.setup()` but one. The new call in `DBSettings.py` is ideal because all modules using django have to call the `django.conf.settings.configure(..)` from there anyway. I cannot remember why we did not call `django.setup()` there in the first place.
=> Fix bcfg2-report-collector for django-1.9

src/lib/Bcfg2/Reporting/Compat.py, src/lib/Bcfg2/Reporting/urls.py, testsuite/install.sh
Django 1.10 removes the patterns method for building the urlpatterns. This adds a simple fallback method into `Reporting/Compat.py`.
=> Fixes for django 1.10

testsuite/install.sh
fedorahosted.org was retired on March 1st, 2017. So we need to pull
python-augeas from anywhere else, let's simply install it with pip
from PyPI.
=> testsuite: Use python-augeas from PyPI with pip

src/lib/Bcfg2/Server/Info.py
This should allow to execute python scripts with indentation through bcfg2-info debug command.
(This is #329 rebased on master.)
=> Fix multiline scripts in bcfg2-info debug mode

src/lib/Bcfg2/Options/Parser.py, testsuite/Testsrc/Testlib/TestOptions/TestConfigFiles.py
If the config file is not available, it should not be a fatal error,
but bcfg2 should just use the default config values.
=> Options: Missing config file is not a fatal error

src/lib/Bcfg2/Server/Info.py
It seems to be, that there must not be any Python statement before the
magic comment.
=> Server/Info: Fix encoding declaration

src/lib/Bcfg2/Server/Plugins/Probes.py
This line brakes django detection for the Probes! It resets the global
variable just after the detection. This line was left while changing
the placement of the detection in fa0d86aba32c40d829f9f94411403221a48283e8.
=> Probes: Remove wrong line

doc/development/caching.txt, doc/server/plugins/grouping/ldap.txt, src/lib/Bcfg2/Server/Cache.py, src/lib/Bcfg2/Server/Plugin/helpers.py, src/lib/Bcfg2/Server/Plugins/Ldap.py, src/lib/Bcfg2/Server/Plugins/Packages/__init__.py
This adds a few more things to the LDAP plugin and removes the issues mentioned in the docs:
- It supports ldaps now, by providing the possibility to set the LDAP URI directly and setting arbitrary options. 
- The plugin does work with all metadata cache modes, because it only caches the available queries in the metadata cache and adds a separate cache for the results. By default it will cache the results until the next client run. But it can be configured by config file, that it should not cache anything (the ldap query is executed on every access) or that it should keep the cache until it is expired manually via XMLRPC. The cache can be expired by query, by hostname or completely.
=> Ldap enhancements

testsuite/install.sh
The older python versions only ship with an old version of pip. Since some days
SSL is required for downloading from pypi. We have to specify this explicitly
because the older pip version only try http by default.
(https://github.com/pypa/pip/issues/4817)
=> travis-ci: Fix pip failure for older python versions

src/lib/Bcfg2/Client/Tools/POSIX/base.py, testsuite/Testsrc/Testlib/TestClient/TestTools/TestPOSIX/Testbase.py
Don't let the client follow symbolic links when changing the owner of a path.
=> POSIX: Don't follow symlinks when changing owner

doc/conf.py, testsuite/install.sh, testsuite/requirements-26.txt
This will fix the testsuite:
* Python 2.6 requires an older version of lxml and PyYAML
* python-mock documentation was removed from voidspace.org.uk
* boto requires google_compute_engine (at least in the python2.6 environment of travis-ci)
=> Fix testsuite

src/lib/Bcfg2/Server/Lint/__init__.py
When importing packages we should not pollute the global modules
namespace and always import new modules with their package name.
Without this fix, I could not import the module `Crypto.Util` in a TemplateHelper while linting, because `Bcfg2.Server.Lint.Crypto` was already imported as `Crypto`.
=> Lint: Import lint plugins with package name

src/lib/Bcfg2/Server/Plugins/Probes.py
Do not encode py3 strings to utf-8 again. Compat.unicode matches strings and unicode in py3.
=> Do not encode py3 strings to utf-8 again.

src/lib/Bcfg2/Reporting/templatetags/bcfg2_tags.py
django-1.8 deprecated referencing views as strings in the url(), so we
need to import the fallback view and referencing the view function
directly.
=> Reporting: Fix add_url_filter fallback

testsuite/install.sh
This should fix the recent travis failure.
=> testsuite: Fix pip index-url for ancient python

src/lib/Bcfg2/DBSettings.py
bcfg2-web will fail without setting a valid time zone in newer django versions. This fix initializes the time zone as utc instead of None, to fix most setups without directly breaking functionality. This can be fixed without changing the code by adding this to the config file.
```
[reporting]
TIME_ZONE = <valid_tz>
```
using UTC is recommended by django: https://riptutorial.com/django/example/3107/setting-the-timezone
=> Fix default timezone in debian buster
