Bcfg2/bcfg2

src/lib/Bcfg2/Server/Plugins/SSHbase.py
Make the public host key data avaialabe for the templates. I do not know if there is something special to do for metadata caching.
=> Make SSHbase also a Connector plugin.

doc/releases/1.4.0pre2.txt, src/lib/Bcfg2/Client/Tools/HomeBrew.py
This a first pass at teaching bcfg2 about homebrew on OSX. Much of this is lifted from the MacPorts.py file.
=> Plugin homebrew

src/lib/Bcfg2/Options.py, src/lib/Bcfg2/Server/CherryPyCore.py, src/lib/Bcfg2/Server/Core.py, src/lib/Bcfg2/Server/MultiprocessingCore.py, src/sbin/bcfg2-info
As requested in #253 this let the server to drop privileges even if not running as daemon (but if running as root).
=> Server/Core: drop privileges even if not running as daemon

doc/client/tools/vcs.txt, doc/server/plugins/generators/rules.txt
=> Add small example for client tools vcs

src/lib/Bcfg2/Server/BuiltinCore.py
python-daemon closes all open files, so we need to specify the filehandles
of the log files to keep logging working.
=> BuiltinCore: Fix logging with daemonization

src/lib/Bcfg2/Reporting/Reports.py
With the filter feature of bcfg2-reports it is possible that all
interactions of a client gets filtered. Now we simply skip those clients
without interactions and do not fail with an exception.
=> Reporting: Do not fail, if no interactions found

src/lib/Bcfg2/Client/Tools/Systemd.py
Add FindExtra to get a listing of all extra systemd entries.
=> Client/Tools/Systemd: Find extra entries

doc/server/encryption.txt, doc/server/plugins/connectors/grouplogic.txt, doc/server/plugins/generators/cfg.txt, doc/server/plugins/grouping/ldap.txt
This are only some small fixes for the docs. Some small formating issues and an update for the lax_decryption setting (The config setting was changed in 919059f0971c0f8bf18ca2cedb3c7e5319632726).
=> Some small fixes for the docs

doc/server/plugins/generators/packages.txt, schemas/pkgtype.xsd, src/lib/Bcfg2/Client/Tools/Pacman.py, src/lib/Bcfg2/Server/Plugins/Packages/Pac.py
* Add dependency resolution (#347).
* Add groups (#348).
I don't know the appropriate way to invalidate the cache here, so it's currently up to the user to remove the old cache file if things break.
=> Improve Pacman support

src/lib/Bcfg2/Reporting/views.py
=> Reporting: Remove invalid select_related

src/lib/Bcfg2/Options/Parser.py
=> Options: Fix default repository path

src/lib/Bcfg2/Server/Admin.py
=> Admin: Remove extraneous quote

doc/man/bcfg2.conf.txt, doc/man/bcfg2.txt, man/bcfg2.1, man/bcfg2.conf.5
Fix a couple of typos in man pages.
=> Manpage typo fixes

src/lib/Bcfg2/Reporting/Storage/DjangoORM.py
=> Reporting: Fix missing sys import

src/lib/Bcfg2/Server/Lint/Bundler.py
=> Server/Lint: Include RequiredBundle in referenced bundles

src/lib/Bcfg2/Reporting/Storage/DjangoORM.py
It wasn't included in the transition from a wildcard import in 255faaf.
=> Reporting/Storage: Import ServiceEntry

src/lib/Bcfg2/Reporting/Storage/DjangoORM.py
=> Reporting: Add POSIX User/Group Entry types

src/lib/Bcfg2/Reporting/Storage/DjangoORM.py
Sorry, I missed this in #388. Are there any others that should be imported here?
=> Reporting/Storage: Import ActionEntry

src/lib/Bcfg2/DBSettings.py, src/lib/Bcfg2/Reporting/Compat.py, src/lib/Bcfg2/Reporting/templates/clients/detail.html, src/lib/Bcfg2/Reporting/templates/clients/detailed-list.html, src/lib/Bcfg2/Reporting/templates/clients/manage.html, src/lib/Bcfg2/Reporting/templates/config_items/common.html, src/lib/Bcfg2/Reporting/templates/config_items/entry_status.html, src/lib/Bcfg2/Reporting/templates/config_items/listing.html, src/lib/Bcfg2/Reporting/templates/displays/summary.html, src/lib/Bcfg2/Reporting/templates/displays/timing.html, src/lib/Bcfg2/Reporting/templates/widgets/interaction_list.inc, src/lib/Bcfg2/Reporting/views.py
This are the remaining fixes for django 1.10. Thanks to @dikim33 for some debugging via IRC.
=> More fixes for Django 1.10

src/lib/Bcfg2/Reporting/Storage/DjangoORM.py
=> Reporting: Add SELinux entries

src/lib/Bcfg2/Server/Core.py, testsuite/install.sh
=> Fix server shutdown
